spring:
  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5430/testerDb
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off
    allow-circular-references: true
  flyway:
    locations:
      - classpath:/db/migration/1.0
      - classpath:/db/migration/data
    enabled: true
    url: jdbc:postgresql://localhost:5430/testerDb
    user: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true